env:
    MANIFEST: git://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
    MANIFEST_BRANCH: twrp-11
    DEVICE: RMX3171
    DT_LINK: https://github.com/iamshubh69/android_recovery_realme_RMX3171
    DT_PATH: device/realme/RMX3171
    TARGET: recoveryimage
    BOTTOKEN: 5166520936:AAFKVuPWWl2Y8gzzy4gOicKQO2iJEhlPaSc

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ubuntu:20.04
      cpu: 8
      memory: 20G
  
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - sudo apt install curl -y
       - sudo apt-get install git -y
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt update -y && sudo apt install git aria2 curl wget rsync zip unzip lzma cpio ccache neofetch -y
       - sudo apt install python2 -y
       - sudo ln -sf /usr/bin/python2 /usr/bin/python
       - git clone https://github.com/akhilnarang/scripts.git ~/scripts
       - cd ~/scripts
       - sudo bash setup/android_build_env.sh
       - cd ~
       - git config --global user.name "aswin11234"
       - git config --global user.email "aswinsanker08@gmail.com"
  
  Sync_script:
      - mkdir -p ~/work
      - cd ~/work
      - repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
      - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - git clone https://github.com/iamshubh69/android_recovery_realme_RMX3171 -b main device/realme/RMX3171

  Build_script:
      - cd ~/work
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export LC_ALL="C"
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - . build/envsetup.sh
      - lunch twrp_RMX3171-eng
      - mka recoveryimage
     
  Upload_script:
      - cd ~/work
      - cd out/target/product/$DEVICE
      - zip -r recovery.img.zip recovery.img
      - for i in *.zip; do curl -F document=@"$i" https://api.telegram.org/bot5166520936:AAFKVuPWWl2Y8gzzy4gOicKQO2iJEhlPaSc/sendDocument?chat_id=-1001524529424; done
        
